### ISSUE TITLE
hello, I have met this error.Does i lack of anything about the pretrained model?

### ISSUE THREAD

**Issue by awhathell** [ChocoWu/LasUIE#4]
Traceback (most recent call last):
  File "/home/LasUIE/run_finetune.py", line 289, in <module>
    model_wrapper = ModelWrapper(**config)
  File "/home/LasUIE/run_finetune.py", line 46, in __init__
    self.model = get_model(self.model_type, self.lm_location)
  File "/home/LasUIE/run_finetune.py", line 35, in get_model
    return model_dict[model_type].from_pretrained(lm_location)
  File "/home/anaconda3/envs/lasuie/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2795, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/anaconda3/envs/lasuie/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3008, in _load_pretrained_model
    raise ValueError(
ValueError: The state dictionary of the model you are trying to load is corrupted. Are you sure it was properly saved?

**Comment by scofield7419** [comment]
Hi, if you are using the framework the first time, you need to first train (finetune) the model, then the second time you may load from checkpoints for incremental fine-tuning or inference.   
So just mark the argument `load_from_checkpoint` as False.

But from the trackback, it seems like the backbone LM parameter is corrupted. Make sure your LM parameter file (e.g., T5-base) works fine. Try to re-download the LM.

**Comment by awhathell** [comment]
Thank you for your reply. I have checked the parameters. The load_from_checkpoints is seted False.&nbsp;
I just follow the README. It says "can directly make 2.3.2 finetuning without post-training."&nbsp;
So I run the finetune program.
When it runs here,it error.
if args.load_from_checkpoint:
    model_wrapper = ModelWrapper.load_from_checkpoint(args.model_checkpoint)
else:
    model_wrapper = ModelWrapper(**config)//this!!!
Does i need to download the "&nbsp;google/flan-t5-base" myself? Does it can download automaticaly when running?
Besides, when will you release the pretrained checkpoint? Looking forward your reply.





***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ChocoWu/LasUIE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月21日(星期五) 下午3:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ChocoWu/LasUIE] hello, I have met this error.Does i lack of anything about the pretrained model? (Issue #4)





 
Hi, if you are using the framework the first time, you need to first train (finetune) the model, then the second time you may load from checkpoints for incremental fine-tuning or inference.
 So just mark the argument load_from_checkpoint as False.

**Comment by scofield7419** [comment]
Hi, if you denote `google/flan-t5-base` in config.json, then it should be automatically downloaded.   
The post-trained checkpoint will be considered to be released the next day, as we are constructing the demo system. But you may directly use the existing LM (e.g., T5-base), and I suggest you do the fine-tuning yourself with your datasets.

**Comment by awhathell** [comment]
Hello, I have confirmed again and again that there are no issues with the settings of the config file or parameters. The problem lies in downloading the flan-t5-base model. Let me list my debugging process for you. Can you help me see where the problem is? thank you very much indeed.



the red line is the step that the program is running.
if args.load_from_checkpoint://(False)
    model_wrapper = ModelWrapper.load_from_checkpoint(args.model_checkpoint)
else:
    model_wrapper = ModelWrapper(**config)class ModelWrapper(LightningModule):
    def __init__(self, dataset, model_type, task_type, lm_location, learning_rate, other_learning_rate, adam_epsilon, warmup_steps, weight_decay,
                 train_batch_size, val_batch_size, max_length, gradient_accumulation_steps, is_train=True):
        super(ModelWrapper, self).__init__()
        self.save_hyperparameters()
        self.model_type = model_type
        self.task_type = task_type
        self.lm_location = lm_location
        self.model = get_model(self.model_type, self.lm_location)


def get_model(model_type, lm_location):
    return model_dict[model_type].from_pretrained(lm_location)
then it goes to the "python3.8/site-packages/transformers/modeling_utils.py".


if dtype_orig is not None:
    torch.set_default_dtype(dtype_orig)

(
    model,
    missing_keys,
    unexpected_keys,
    mismatched_keys,
    offload_index,
    error_msgs,
) = cls._load_pretrained_model(//跳转
    model,
    state_dict,
    loaded_state_dict_keys,  # XXX: rename?
    resolved_archive_file,
    pretrained_model_name_or_path,
    ignore_mismatched_sizes=ignore_mismatched_sizes,
    sharded_metadata=sharded_metadata,
    _fast_init=_fast_init,
    low_cpu_mem_usage=low_cpu_mem_usage,
    device_map=device_map,
    offload_folder=offload_folder,
    offload_state_dict=offload_state_dict,
    dtype=torch_dtype,
    load_in_8bit=load_in_8bit,
    keep_in_fp32_modules=keep_in_fp32_modules,
)
# Make sure we are able to load base models as well as derived models (with heads)
start_prefix = ""
model_to_load = model
if len(cls.base_model_prefix) &gt; 0 and not hasattr(model, cls.base_model_prefix) and has_prefix_module:
    start_prefix = cls.base_model_prefix + "."
if len(cls.base_model_prefix) &gt; 0 and hasattr(model, cls.base_model_prefix) and not has_prefix_module:
    model_to_load = getattr(model, cls.base_model_prefix)
    base_model_expected_keys = list(model_to_load.state_dict().keys())
    if any(key in expected_keys_not_prefixed and key not in base_model_expected_keys for key in loaded_keys):
        raise ValueError(
            "The state dictionary of the model you are trying to load is corrupted. Are you sure it was "
            "properly saved?"
        )


where it error as follows:
File "/home/anaconda3/envs/lasuie/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2795, in from_pretrained
&nbsp; &nbsp; ) = cls._load_pretrained_model(File"/home/anaconda3/envs/lasuie/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3008, in _load_pretrained_model
&nbsp; &nbsp; raise ValueError(
ValueError: The state dictionary of the model you are trying to load is corrupted. Are you sure it was properly saved?


***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ChocoWu/LasUIE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月21日(星期五) 下午3:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ChocoWu/LasUIE] hello, I have met this error.Does i lack of anything about the pretrained model? (Issue #4)





 
Hi, if you denote google/flan-t5-base in config.json, then it should be automatically downloaded.
 The post-trained checkpoint will be considered to be released the next day, as we are constructing the demo system. But you may directly use the existing LM (e.g., T5-base), and I suggest you do the fine-tuning yourself with your datasets.

**Comment by scofield7419** [comment]
That's pretty weird. Try manually download the Flan-T5-base model yourself at one specific fold. Then specify the LM-file with your own path.  
Or, change the Flan-T5-base with T5-base.

**Comment by scofield7419** [comment]
Seems solved. I'll close this one.
