### ISSUE TITLE
How can i use this model with the chinese datasets?

### ISSUE THREAD

**Issue by awhathell** [ChocoWu/LasUIE#5]
hello, I ran through the code using the dataset provided in the project, but it seems that the T5 model is not suitable for Chinese. Is there a way for me to run the code using the Chinese dataset

**Comment by ChocoWu** [comment]
Hi, that's quite easy; maybe you should use a Chinese version of T5-like backbone LM instead.

**Comment by scofield7419** [comment]
@awhathell Here some Chinese T5, FYI:
https://huggingface.co/uer/t5-base-chinese-cluecorpussmall
https://huggingface.co/Langboat/mengzi-t5-base
https://huggingface.co/lemon234071/t5-base-Chinese

And Chinese BART:
https://huggingface.co/fnlp/bart-base-chinese
